version: '3'

services:
  application:
    build: ./application
    command: npm start
    volumes:
      - ./application:/app
    ports:
      - 5000:3000
    environment:
      NODE_ENV: development
      PORT: 3000
    depends_on:
      - authentication-service
      - message-service

  nginx:
    image: nginx
    ports:
        - "9000:80"
    environment:
        NGINX_PORT: 80
    volumes:
        - ./compose-resources/nginx:/etc/nginx
    depends_on:
      - authentication-service
      - message-service
      - application
    restart: always
    # networks:
    #     - internal

  authentication-service:
    build: ./authentication
    environment:
      - JWT_KEY="${JWT_KEY}"
    volumes:
      - ./authentication:/app
    ports:
      - 5001:3000

  message-service:
    build: ./message
    environment:
      - JWT_KEY="${JWT_KEY}"
    volumes:
      - ./message:/usr/src/app
    ports:
      - 5002:3000

# networks:
#     internal:
#         driver: bridge
#         ipam:
#             driver: default
#             config:
#             - subnet: 172.16.2.0/24
#               gateway: 172.16.2.1
